import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { DEFAULT_CONFIG } from "../src/core/config.js";
import { checkFile } from "../src/policies/index.js";

describe("checkFile: zero-ai-attribution does not scan documentation files", () => {
  it("passes the repo's own generated CLAUDE.md template, which discusses AI attribution as a topic", async () => {
    const template = readFileSync(path.join(process.cwd(), "templates", "CLAUDE.md"), "utf8");
    const report = await checkFile("CLAUDE.md", "", template, DEFAULT_CONFIG);
    expect(report.ok).toBe(true);
  });

  it("passes the same text as a .txt file too", async () => {
    const report = await checkFile("notes.txt", "", "Do not add AI-generated notices or Co-Authored-By trailers.", DEFAULT_CONFIG);
    expect(report.ok).toBe(true);
  });

  it("still fails real attribution inside a source file", async () => {
    const report = await checkFile("src/app.js", "", "// Generated by Claude\nconsole.log(1);\n", DEFAULT_CONFIG);
    expect(report.ok).toBe(false);
  });
});
