import { describe, expect, it } from "vitest";
import { DEFAULT_CONFIG } from "../src/core/config.js";
import { checkZeroAiAttribution } from "../src/policies/zero-ai-attribution.js";

const config = DEFAULT_CONFIG.policies["zero-ai-attribution"];

describe("zero-ai-attribution", () => {
  const casesThatShouldFail = [
    "Generated by Claude",
    "Generated with Claude",
    "Generated with Claude Code",
    "Generated by ChatGPT",
    "Generated by Codex",
    "AI-generated",
    "AI generated",
    "Assisted by Claude",
    "Assisted-by: Claude",
    "https://claude.ai/chat/abc123",
    "🤖 Generated with Claude Code",
  ];

  for (const text of casesThatShouldFail) {
    it(`fails on: ${text}`, () => {
      const report = checkZeroAiAttribution(text, config);
      expect(report.ok).toBe(false);
    });
  }

  const casesThatShouldPass = [
    'const provider = "Anthropic";',
    "This SDK wraps the Anthropic API.",
    "We evaluated OpenAI, Anthropic and Cohere for this integration.",
    "Copilot-friendly type hints improve autocomplete.",
    "See docs for GitHub Copilot compatibility notes.",
  ];

  for (const text of casesThatShouldPass) {
    it(`passes on: ${text}`, () => {
      const report = checkZeroAiAttribution(text, config);
      expect(report.ok).toBe(true);
    });
  }

  it("honors custom patterns", () => {
    const withCustom = { ...config, "custom-patterns": ["written by our internal bot"] };
    const report = checkZeroAiAttribution("This file was written by our internal bot.", withCustom);
    expect(report.ok).toBe(false);
  });

  it("can be disabled per-provider via config", () => {
    const openaiOnly = { ...config, providers: ["openai"] };
    const report = checkZeroAiAttribution("Generated by Claude", openaiOnly);
    expect(report.ok).toBe(true);
  });
});
